### ISSUE TITLE
The code is incomplete and cannot be run

### ISSUE THREAD

**Issue by violin0847** [Pose-Group/FAMI-Pose#2]
The code is incomplete and cannot be run, please give a runnable code, thank you.

**Comment by violin0847** [comment]
> The code is incomplete and cannot be run, please give a runnable code, thank you.
For example:
- `from datasets.zoo.jhmdb.pose_topology import JHMDB_Keypoint_Ordering` in file  `datasets/process/structure/keypoints_ord.py`, where is `jhmdb` module?
- etc.

**Comment by 1223s** [comment]
I had the same problem

**Comment by violin0847** [comment]
Looking forward to your reply. @BII-wushuang @chenhaomingbob @FRunyang
